<?php

namespace AppBundle\Repository;

/**
 * SubscriberOptOutDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberOptOutDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
