<?php

namespace AppBundle\Repository;

/**
 * SubscriberOptInDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberOptInDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
