<?php

namespace AppBundle\Repository;

/**
 * SubscriberDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
