<?php

namespace AppBundle\Repository;

/**
 * UnsubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnsubscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
